version: '3.6'
services:
  api-videolibrary:
    build: api
    volumes:
      - ../code:/var/www/html/videolibrary
    links:
      - db-videolibrary
  nginx-videolibrary:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../code:/var/www/html/videolibrary
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ../log:/var/log/videolibrary
    links:
      - api-videolibrary
  db-videolibrary:
    image: library/mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=videolibrary
      - MYSQL_USER=videolibrary_user
      - MYSQL_PASSWORD=1234
