version: '3.6'
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    volumes:
      - ../code:/var/www/html/videolibrary
    links:
      - db
    networks:
      - videolibrary
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../code:/var/www/html/videolibrary
      - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - api
    networks:
      - videolibrary
  db:
    image: library/mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=videolibrary
      - MYSQL_USER=videolibrary_user
      - MYSQL_PASSWORD=1234
    networks:
      - videolibrary
networks:
  videolibrary:
    driver: bridge
