services:
  api.controller.videos.getVideos:
    class: Videolibrary\Api\Infrastructure\Ui\Http\Controller\Videos\GetVideosController
    arguments:
      - '@api.query.video.getVideosHandler'
    public: true