services:
    api.repository.inMemoryVideoRepository:
        class: App\Videolibrary\Api\Infrastructure\Persistence\InMemory\Repository\InMemoryVideoRepository
    api.repository.doctrineVideoRepository:
        class: App\Videolibrary\Api\Infrastructure\Persistence\Doctrine\Repository\DoctrineVideoRepository
        arguments:
            - '@doctrine.orm.default_entity_manager'